"""user currentstate

Revision ID: 3e394918051b
Revises: 7d1a97b5cae8
Create Date: 2020-04-03 22:06:51.326148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e394918051b'
down_revision = '7d1a97b5cae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('current_state', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'current_state')
    # ### end Alembic commands ###
