"""user table

Revision ID: ca2c4f5ba707
Revises: c786956724f1
Create Date: 2020-02-27 23:31:13.021030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca2c4f5ba707'
down_revision = 'c786956724f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_drinks_drinkTime'), 'drinks', ['drinkTime'], unique=False)
    op.add_column('user', sa.Column('private_stat', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_user_regtime'), 'user', ['regtime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_regtime'), table_name='user')
    op.drop_column('user', 'private_stat')
    op.drop_index(op.f('ix_drinks_drinkTime'), table_name='drinks')
    # ### end Alembic commands ###
